server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://61.97.187.175:3306/octopus?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yongbin
    password: Yongbin123!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  resources:
    add-mappings: true

jwt:
  secret-key: iocyuiasfmlfksdciohvb1j23iuoch32iujbj2kbjkbjkk1l
  access-exp: 10000
  refresh-exp: 10000